<a href="https://colab.research.google.com/github/williammcintosh/machine_learning_projects/blob/main/Singular_Value_Decomposition_SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Singular Value Decomposition
Iris SVD example: https://www.cs.cmu.edu/afs/cs.cmu.edu/academic/class/15750-s20/www/notebooks/SVD-irises-clustering.html


$A$ is $m\times n$

$A^TA$ is $n\times n$ (Covariance matrix if A is a dataset where the columns have mean 0 then $A^TA/(n-1)$)

$ \sigma_i = \sqrt{\lambda_i} = ||Aq_i||$

$\lambda_i$ is an eigenvalue of $A^TA$
$q_i$ is the associated eigenvector

$\sigma_1 \geq \sigma_2 \geq \dots \geq \sigma_r \geq 0$

$r=rank(A)$

A singular value decomposition of $A$

$A = P \Sigma_A Q^T$

$P^TP=I$

$Q^TQ=I$

$\Sigma_A = \begin{pmatrix}
\sigma_1 & 0 & 0 \\
0 & \sigma_2 & 0
\end{pmatrix}$

Columns of $P$ form an Orthonormal basis of $\mathbb{R}^m$

Columns of $Q$ form an Orthonormal basis of $\mathbb{R}^n$


Existence of this decomposition relies on:

$A^TA$ has real non-negative eigenvalues

$(A^TA)^T = ((A)^T (A^T)^T) = A^TA$ So $A^TA$ is symmetric and must have an orthonormal set of eigenvectors


## Example

$$A = \begin{pmatrix}
1 & 0 & 1\\
-1 & 1 & 0\\
\end{pmatrix}$$

Goal: $A = P \Sigma_A Q^T$

$$A^TA =
\begin{pmatrix}
1& -1\\
0& 1\\
1& 0\\
\end{pmatrix}
\begin{pmatrix}
1 & 0 & 1\\
-1 & 1 & 0\\
\end{pmatrix} = \begin{pmatrix}
2 & -1 & 1\\
-1 & 1 & 0\\
1 & 0 & 1\\
\end{pmatrix}$$

Eigenvalues of $A^TA$

$$det(\lambda I - A^TA) =0 = (\lambda-3)(\lambda-1)\lambda$$

$\lambda_1 = 3$ 

$\lambda_2 = 1$ 

$\lambda_3 = 0$


$q_1 = \frac{1}{\sqrt{6}} \begin{pmatrix}
2 \\
-1\\
1 
\end{pmatrix}$

$q_2 = \frac{1}{\sqrt{2}} \begin{pmatrix}
0 \\
1\\
1 
\end{pmatrix}$

$q_3 = \frac{1}{\sqrt{3}} \begin{pmatrix}
-1 \\
-1\\
1 
\end{pmatrix}$


$Q=[q_1 q_2 q_3]$

$\Sigma_A = \begin{pmatrix}
\sqrt{3} & 0 & 0\\
0 & \sqrt{1} & 0
\end{pmatrix}$

$P = [\frac{Aq_1}{||Aq_1||}  \frac{Aq_2}{||Aq_2||}]$ 

$P$ is $2\times 2$

$\Sigma_A$ is $2\times 3$

$Q$ is $3 \times 3$

In [1]:
import numpy as np

A = np.array([[1, 0,1 ],[-1,1,0]])


In [2]:
A

array([[ 1,  0,  1],
       [-1,  1,  0]])

eigensystem of $A^TA$

In [3]:
evals, evects = np.linalg.eig(A.transpose()@A)

In [4]:
evals

array([ 3.00000000e+00, -2.91433544e-16,  1.00000000e+00])

In [5]:
evects

array([[-8.16496581e-01,  5.77350269e-01, -1.57009246e-16],
       [ 4.08248290e-01,  5.77350269e-01,  7.07106781e-01],
       [-4.08248290e-01, -5.77350269e-01,  7.07106781e-01]])

In [6]:
evects[:,0]

array([-0.81649658,  0.40824829, -0.40824829])

In [7]:
Q = np.column_stack((evects[:,0],  evects[:,2], evects[:,1]))

In [8]:
Q

array([[-8.16496581e-01, -1.57009246e-16,  5.77350269e-01],
       [ 4.08248290e-01,  7.07106781e-01,  5.77350269e-01],
       [-4.08248290e-01,  7.07106781e-01, -5.77350269e-01]])

In [9]:
np.linalg.norm(A@evects[:,0])

1.7320508075688772

In [10]:
p1 = A@evects[:,0]/np.linalg.norm(A@evects[:,0])
p2 = A@evects[:,2]/np.linalg.norm(A@evects[:,2])

In [11]:
print(np.linalg.norm(p1))
print(np.linalg.norm(p2))

1.0
1.0


In [12]:
P = np.column_stack((p1, p2))

In [13]:
Q.transpose()@Q

array([[ 1.00000000e+00, -1.31832700e-16, -1.83191866e-16],
       [-1.31832700e-16,  1.00000000e+00, -3.59450705e-16],
       [-1.83191866e-16, -3.59450705e-16,  1.00000000e+00]])

In [14]:
P.transpose()@P

array([[ 1.00000000e+00, -1.21168839e-16],
       [-1.21168839e-16,  1.00000000e+00]])

In [15]:
SigmaA = np.array([[np.sqrt(evals[0]),0,0],[0,np.sqrt(evals[2]),0]])

In [16]:
SigmaA

array([[1.73205081, 0.        , 0.        ],
       [0.        , 1.        , 0.        ]])

In [17]:
P@SigmaA@Q.T

array([[ 1.00000000e+00,  5.48888227e-17,  1.00000000e+00],
       [-1.00000000e+00,  1.00000000e+00, -1.01465364e-17]])

In [18]:
A

array([[ 1,  0,  1],
       [-1,  1,  0]])

In [19]:
np.linalg.svd(A)

(array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([1.73205081, 1.        ]),
 array([[-8.16496581e-01,  4.08248290e-01, -4.08248290e-01],
        [-1.19879883e-16,  7.07106781e-01,  7.07106781e-01],
        [-5.77350269e-01, -5.77350269e-01,  5.77350269e-01]]))

In [20]:
P

array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]])